global: # Prometheus의 전역(Global) 설정을 시작
  scrape_interval: 15s # 15초마다 한 번씩 대상(cAdvisor 등)으로부터 지표 데이터를 긁어옵니다(Scrape).

scrape_configs: # 데이터를 수집할 대상(Target)들의 목록을 설정
  - job_name: 'cadvisor' # 이 수집 작업의 이름을 'cadvisor'라고 붙입니다.
    static_configs: # 동적이 아닌 고정된 IP나 도메인(여기서는 컨테이너 이름)을 대상으로 설정합니다.
      - targets: ['cadvisor:8080'] # 도커 내부 네트워크를 통해 'cadvisor' 컨테이너의 8080 포트로 접속해 데이터를 가져옵니다.