# Generated by Django 6.0.1 on 2026-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "전체 공개"), ("PRIVATE", "비공개")],
                default="PUBLIC",
                help_text="게시글의 공개 범위를 설정합니다.",
                max_length=10,
            ),
        ),
    ]
