# Generated by Django 6.0.1 on 2026-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="series_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
