# Generated by Django 6.0.1 on 2026-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_series_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="post/thumbnails/%Y/%m/%d/"
            ),
        ),
    ]
