# Generated by Django 6.0.1 on 2026-03-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
